name = "lower-ideal-determinant"
version = "0.1.0"
defaultTargets = ["LowerIdealDeterminant"]

[leanOptions]
pp.unicode.fun = true

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.30.0"

[[lean_lib]]
name = "CompoundDeterminant"

[[lean_lib]]
name = "LowerIdealDeterminant"
